
const SHORT_TYPE_CHART = 'chart'
const SHORT_TYPE_TEXT = 'text'
const SHORT_TYPE_PROGRESS = 'progress'
const SHORT_TYPE_COUNTER = 'counter'

exports.SHORT_TYPE_CHART     = SHORT_TYPE_CHART
exports.SHORT_TYPE_TEXT     = SHORT_TYPE_TEXT
exports.SHORT_TYPE_PROGRESS = SHORT_TYPE_PROGRESS
exports.SHORT_TYPE_COUNTER  = SHORT_TYPE_COUNTER 
