'use strict'

const async = require('async')
const lodash = require('lodash')
const logger = require('../../lib/logger')('service:resource:template')

const ResourceTemplateModel = require('../../entity/resource/template').Entity;
const MonitorTemplateModel = require('../../entity/monitor/template').Entity;
const MonitorModel = require('../../entity/monitor').Entity;
const ResourceModel = require('../../entity/resource').Entity;

const MonitorService = require('./monitor')

module.exports = {
  /**
   *
   * @author Facundo
   * @param {HostGroup} hostgroup
   * @param {Array Resource} resources
   * @param {Customer} customer
   * @param {User} user
   * @param {Function} done
   *
   */
  createTemplates (hostgroup, resources, customer, user, done) {
    if (!resources) return done(null, [])
    if (!Array.isArray(resources) || resources.length===0) return done(null, [])

    logger.log('processing %s resource monitors', resources.length);

    /* create templates from input */
    async.map(
      resources,
      (resource, next) => {
        const monitor = resource.monitor

        if (!monitor) {
          const err = new Error('resource monitor data not defined')
          err.statusCode = 400
          err.resource = resource
          return next(err)
        }

        const config = lodash.assign({}, monitor, monitor.config||{})
        const result = MonitorService.validateData(config)

        if (!result || result.errors) {
          const msg = 'invalid resource monitor data'
          logger.error(msg)
          const e = new Error(msg)
          e.statusCode = 400
          e.info = result.error
          return next(e)
        }

        const data = result.data
        data.customer = customer
        // DO NOT UN-COMMENT ! user property generates conflict with monitor.config.user property of monitor.type === file 
        //data.user = user
        data.hostgroup = hostgroup
        data.source_monitor_id = (resource.monitor._id || resource.monitor.id)
        data.source_resource_id = (resource._id || resource.id)

        logger.log('creating template')
        createResourceTemplate(data,next)
      },
      (err, templates) => {
        if (err) {
          logger.error('failed to create resource template')
          logger.error(err, err.resource)
          return done(err)
        }
        done(null, templates)
      }
    )
  }
}

/**
 * create resource and monito from input
 * @author Facundo
 * @param {Object} input
 * @param {Function(ErrorObject,Object)} done
 */
const createResourceTemplate = (input, done) => {
  const data = {
    hostgroup: input.hostgroup,
    hostgroup_id: input.hostgroup._id,
    customer: input.customer,
    customer_id: input.customer._id,
    customer_name: input.customer.name,
    //user_id: input.user._id,
    //user: input.user,
    type: input.type,
    name: input.name,
    description: input.description,
  }

  MonitorService.setMonitorData(
    input.type,
    lodash.assign({},input,data),
    (err,monitor_data) => {
      if (err) {
        logger.error(err)
        return done(err)
      }

      if (!monitor_data) {
        var e = new Error('invalid resource data')
        e.statusCode = 400
        return next(e)
      }

      monitor_data.source_model_id = input.source_monitor_id
      delete monitor_data.host_id // not needed. just in case...
      delete monitor_data._id // must be autogenerated

      logger.log ('creating monitor template')
      MonitorTemplateModel.create(monitor_data, (err, monitorTemplate) => {
        if (err) {
          logger.error(err, err.errors)
          return done(err)
        }

        data.monitor_template = monitorTemplate._id
        data.monitor_template_id = monitorTemplate._id
        data.source_model_id = input.source_resource_id

        logger.log ('creating resource template')
        ResourceTemplateModel.create(data, (err, resourceTemplate) => {
          if (err) {
            logger.error(err, err.errors)
            return done(err)
          }
          
          if (!resourceTemplate) {
            const err = new Error('Resource template could not be generated')
            return done(err)
          }

          monitorTemplate.template_resource = resourceTemplate._id
          monitorTemplate.template_resource_id = resourceTemplate._id
          monitorTemplate.save()

          resourceTemplate.monitor_template = monitorTemplate // already populated
          logger.log('all templates created')
          done(null,resourceTemplate)
        })
      })
    }
  )
}
